# Generated by Django 4.1 on 2022-08-30 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_examplemodel_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplemodel',
            name='img',
        ),
    ]
